name: car_route_app_assessment_technonext
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk:  ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  logger: ^2.6.1
  location: ^8.0.1
  geocoding: ^4.0.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.1.4
  flutter_screenutil: ^5.9.3
  google_maps_flutter: ^2.12.3
  flutter_easyloading: ^3.0.5
  flutter_polyline_points: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/png/
    - .env