name: car_route_app_assessment_technonext
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk:  ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  intl: ^0.20.2
  path: ^1.9.1
  logger: ^2.6.1
  shimmer: ^3.0.0
  #  marquee: ^2.3.0
  timeago: ^3.7.1
  location: ^8.0.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  #  upgrader: ^11.4.0
  #  geocoding: ^4.0.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.2
  flutter_dotenv: ^5.2.1
  flutter_animate: ^4.5.2
  dropdown_button2: ^2.3.9
  connectivity_plus: ^6.1.4
  flutter_screenutil: ^5.9.3
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  google_maps_flutter: ^2.12.3
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.4
  flutter_polyline_points: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/png/
    - .env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
